site_name: Backup Manager
use_directory_urls: false
repo_url: https://github.com/gserpa24/backup_manager
repo_name: gserpa24/backup_manager
theme:
  icon:
    repo: fontawesome/brands/git-alt
  name: material
  palette:
    scheme: slate
    primary: black
    accent: green
  language: es
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.expand
    - navigation.footer
    - content.tabs.link
    - content.code.copy
    - content.code.select
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gserpa24
    - icon: fontawesome/brands/linkedin
      link: https://github.com/gserpa24
  generator: false
copyright: Copyright &copy; 2024 Gustavo Serpa
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Inicio: index.md
  - Guía:
      - Instalación: guide/installation.md
      - Uso: guide/usage.md
  - Configuracion Avanzada: advanced/configuration.md
  - FAQ: faq.md
